"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import path from "path";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname();
  const notNavBar = ["/login", "/signup", "/login/sso"]
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* flex */}
        <div className="flex flex-col">
          <Image
            src="/header-image.png"
            alt="header image"
            width={1920}
            height={10}
          />
          <Link
            className="font-bold absolute left-[1300px] top-[42px] inline-block align-baseline text-white hover:text-black p-2"
            href={pathName == "/login" ? "/signup" : "/login"}
          >
            {pathName == "/login" ? "Sign Up" : "Login"}
          </Link>
          <div className={`flex flex-row  ${notNavBar.includes(pathName) ? 'items-center justify-center' : ''}`}>
            {!notNavBar.includes(pathName) && <Sidebar />}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
